mutation updateProduct(
  $text_productId: Float!
  $text_name: String!
  $text_price: Float!
  $text_categoryId: Float!
) {
  updateProduct(
    input: {
      id: $text_productId
      name: $text_name
      price: $text_price
      categoryId: $text_categoryId
    }
  ) {
    name
    price
    categoryId
  }
}
